sacoleirosapp/config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
  resources :send_mail, only: [:edit, :create]
  resources :categories, except: [:show]
  resources :admins, except: [:show]
  get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_detail, only: [:show]

  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }
  
  root 'site/home#index'

end

sacoleirosapp/app/models/ad.rb
class Ad < ActiveRecord::Base

  # Callbacks
  before_save :md_to_html

  # Associations
  belongs_to :category, counter_cache: true
  belongs_to :member

  # Validates
  validates :title, :description_md, :description_short, :category, :picture, :finishi_date, presence: true
  validates  :price, numericality: { greater_than: 0 }

  # Scope
  scope :descending_order, ->(quantity = 9) { limit(quantity).order(created_at: :desc) }
  scope :to_the, -> (member) { where(member: member) }

  # paperclip
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  
  # gem money_rails
  monetize :price_cents

  private
    def md_to_html
      options = {
    filter_html: true,
    link_attributes: {
      rel: "nofollow",
      target: "_blank"
    }
    }

    extensions = {
    space_after_headers: true,
    autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    self.description = markdown.render(self.description_md)
    end
    end

sacoleirosapp/app/models/admin.rb
class Admin < ActiveRecord::Base

  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}
  # Enums
	enum role: ROLES
  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access])}
	scope :with_restricted_access, -> { where(role: ROLES[:restricted_access])}

	def self.with_full_access
		where(role: 'full_access')
	end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

sacoleirosapp/app/models/category.rb
class Category < ActiveRecord::Base
	
	# Associations
	has_many :ads
	# Validates
	validates_presence_of :description

	#Scope
	scope :order_by_description, -> { order(:description) }
end

sacoleirosapp/app/models/member.rb
class Member < ActiveRecord::Base
	has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

sacoleirosapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# Pundit
	include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # manages Pundit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	layout :layout_by_resource

	  protected

	  def layout_by_resource
	  	if devise_controller? && resource_name == :admin
			"backoffice_devise"
		elsif devise_controller? && resource_name == :member
			"site_devise"
		else
			"application"
		end
	end

	def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar esta ação."
    redirect_to(request.referrer || root_path)
  end
end

sacoleirosapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
   before_action :set_admin, only: [:edit, :update, :destroy]
   after_action :verify_authorized, only: [:new, :destroy]
   after_action :verify_policy_scoped, only: :index

  def index
  	# @admins = Admin.all
    # @admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end

  def new
  	@admin = Admin.new
    authorize @admin
  end

  def create
  	@admin =Admin.new(params_admin)
  	if @admin.save 
  		redirect_to backoffice_admins_path, notice: "O administrador #{@admin.email} foi criado com sucesso"
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
  		redirect_to backoffice_admins_path, notice: "O administrador #{@admin.email} foi atualizado com sucesso"
  	else
  		render :edit
  	end
  end

  def destroy
    authorize @admin
    admin_name = @admin.name
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O administrador #{admin_name} foi excluído com sucesso"
  else
    render index
  end
  end

  private

  def set_admin
  	@admin = Admin.find(params[:id])
  end

  def params_admin
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)
    end

    if @admin.blank? 
  	 params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  
  end
  def password_blank?
    params[:admin][:password].blank? && 
    params[:admin][:password_confirmation].blank?
  end
end

sacoleirosapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout "backoffice"

	def pundit_user
		current_admin # current_user to Pundit
	end
end

sacoleirosapp/app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  protected
    def after_sign_in_path_for(resource)
      site_profile_dashboard_index_path
    end
end

sacoleirosapp/app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController

	def show
		@ad = Ad.find(params[:id])
	end
end

sacoleirosapp/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
  	@categories = Category.order_by_description
  	@ads = Ad.descending_order
  end
end

sacoleirosapp/app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
 layout "profile"
end

sacoleirosapp/app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout "site"
end

sacoleirosapp/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

sacoleirosapp/app/helpers/application_helper.rb
module ApplicationHelper
end

sacoleirosapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
	OptionsForRoles = Struct.new(:id, :description)

	def options_for_roles
		Admin.roles_i18n.map do |key, value|
			OptionsForRoles.new(key, value)
		end
	end
end

sacoleirosapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

sacoleirosapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

sacoleirosapp/app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

sacoleirosapp/app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

sacoleirosapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

sacoleirosapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end -%>
        </ul>
    </div>
<% end -%>
<div class="panel panel-default">
    <div class="panel-heading">
        <%= action%>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
        <%= form_for ([:backoffice, @admin]) do |f| %>    
            <div class="form-group">
                <%= f.label :nome %>
                <%= f.text_field :name, class:"form-control", placeholder:"Nome do administrador"%>
            </div>

            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class:"form-control", placeholder:"Email do administrador"%>
            </div>
            
            <% if policy(@admin).edit? %>
            <div class="form-group">
                <%= f.label :role %>
                <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                <div class="radio">
                    <%= b.label {b.radio_button + b.text} %>
                </div>
                <% end -%>
            </div>
            <% end -%>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class:"form-control", placeholder:"Senha do admnistrador" %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da senha" %>
            </div>
            <button type="submit" class="btn btn-default">Salvar</button>
            <% end -%>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
            
            

sacoleirosapp/app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
             <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('labels.close') %></button>
        <%= submit_tag t('labels.send_message'), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

sacoleirosapp/app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Sacoleirosapp - Administração</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li><%= current_admin.email %></li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
            <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                    <i class="fa fa-sign-out fa-fw"></i> 
                    Sair
                    <% end %>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <%= link_to backoffice_path do %>
                        <i class="fa fa-dashboard fa-fw"></i> Painel
                        <% end %>
                    </li>
                    <li>
                        <%= link_to backoffice_categories_path do %>
                        <i class="fa fa-th-list fa-fw"></i> Categorias</a>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to backoffice_admins_path do %>
                        <i class="fa fa-users fa-fw"></i> Administradores</a>
                        <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

sacoleirosapp/app/views/layouts/shared/_notifications.html.erb
<% if notice %>
        <%= javascript_tag "$.notify( { message: '#{notice}'}, { type:'success', placement: {
										from: 'top',
										align: 'center'}});" %>
<% end -%>
<% if alert %>
    <%= javascript_tag "$.notify( { message: '#{alert}'}, { type:'danger', placement: {
										from: 'top',
										align: 'center'}});" %>
<% end -%>

sacoleirosapp/app/views/layouts/site_shared/_footer.html.erb
<div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <%= t('app.name') %> <%= Date.today.year %></p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

sacoleirosapp/app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to t('app.name'), root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right">
                    <% unless member_signed_in? %>
                        <li>
                            <%= link_to "Login", new_member_session_path %>
                        </li>
                        <li>
                            <%= link_to "Cadastrar-se", new_member_registration_path %>
                        </li>
                    <% else %>
                        <li>
                            <%= link_to current_member.email, "#" %>
                        </li>
                        <li>
                            <%= link_to "Perfil", site_profile_dashboard_index_path %>
                        </li>
                        <li>
                            <%= link_to "Sair", destroy_member_session_path, method: :delete %>
                        </li>
                    <% end -%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>